@c Section 2: Narrativa
@node Narrativa
@section Narrativa

@menu
* Sinopsis narrativa:: ...
* Tema y tono:: ...
* Género narrativo y Recursos de género:: ...
* Personajes:: ...
@end menu

@c Subsection 1: Sinopsis narrativa
@node Sinopsis narrativa
@subsection Sinopsis narrativa

@i{MetalBirlant} se basa en un planeta-ciudad levantado sobre un agujero negro se produce una anomalia espacio-tiempo, donde si bajas a plantas inferiores avanzaras en el tiempo hacia el futuro y si subes retrocedes hasta el presente. La economía de este planetoide se basa en el sky gold, un metal que no tiene más existencias. 

El protagonista, Elon CEO de T€$la® , utiliza NFTs mandandolos al futuro para extraer reservas futuras de este metal. Pero su versión futura no está precisamente contenta con esta acción, dado que le está robando a él mismo, por lo que decide entrar en acción atacando a su versión pasada.

@c Subsection 2: Tema y tono
@node Tema y tono
@subsection Tema y tono

Comedia/Humor, encontrada en cualquier tipo de cómic.

@c Subsection 3: Género narrativo y Recursos de género
@node Género narrativo y Recursos de género
@subsection Género narrativo y Recursos de género

Relato tipo cómic.

@c Subsection 4: Personajes
@node Personajes
@subsection Personajes

@itemize @bullet
@item
Elon J. D'Oroski (presente) - Personaje protagonista, CEO de T€$la® . Le sustrae T€$las a su versión futura inconscientemente de las consecuencias.
@item
Elon J. D'Oroski (futuro) - Personaje antagonista. Víctima de los hurtos de su versión pasada.
@item
NFT (nativos forzosamente trabajadores) - Personajes extra.
@end itemize
