@c Section 2: Control y Diseño de Interfaz
@node Control y Diseño de Interfaz
@section Control y Diseño de Interfaz

@menu
* Reglas de control del Juego/Personaje:: ...
* Listado/Tabla de inputs y acciones:: ...
* Diseño de Interfaz/GUI:: ...
* @i{Wireframes} de interfaz:: ...
* Diagramas de contextos/flujo:: ...
@end menu

@c Subsection 1: Reglas de control del Juego/Personaje
@node Reglas de control del Juego/Personaje
@subsection Reglas de control del Juego/Personaje

Turno del futuro:
* Las zonas de trampas son las zonas en que podemos poner una trampa con el menu de trampas.
* Las zonas de trampas en cada fase son configuradas de antemano estrategcamente con el intuito de mantener el equilibrio del juego y evitar 
bugs o errores en el sistema de incentivo.
* El cursor solo puede moverse hacia cuatro direcciónes (izquierda, derecha, hacia arriba y hacia abajo).
* Se puede cancelar la colocacion de una trampa si hacemos click en la trampa con el boton deracho del ratón.
* Existen unos limites de espacio dentro de cada zona de trampas para evitar errores en el caso de que se compre dos trampas o mas en una misma zona.
* Existen plataformas que se mueven, aunque en el turno del futuro estaran estáticas. Habran indicadores (flechas y lineas) de como estas plataformas 
se moverán en el turno del presente.

Turno del presente:
* El juego incentiva al jugador a direccionar el personaje hacia abajo con el movimiento de la camara. 
* El limite superior de la pantalla es solida (el personaje no lo puede ultrapasar). 
* La camara sigue al personaje.
* El personaje tiene una cantidad de vidas (sistema de corazones) que pierde cuande es golpeado por un obstaculo o trampa.
* El personaje solo puede caminar por las plataformas (no existen zonas donde se pueda volar o nadar).
* Si el personaje no esta encima de una plataforma, esta cayendo.

@c Subsection 2: Listado/Tabla de inputs y acciones
@node Listado/Tabla de inputs y acciones
@subsection Listado/Tabla de inputs y acciones

Turno del futuro:
Flechas o ratón: Moverse en el mapa con un cursor / Seleccionar categoria de trampas y trampa en el menu de trampas.
Tecla C / boton izquierdo del ratón: Seleccionar trampa (en el menu o en el mapa)
Botón izquierdo del ratón: Seleccionar sitio en el mapa donde se colocara la trampa seleccionada.
Tecla V: Sacar trampa seleccionada del mapa.
Tecla Z: Terminar turno. Ir al turno del presente.

Turno del Presente:
Flecha izquierda / Tecla A: Mover el personaje a la izquierda.
Flecha derecha / Tecla D: Mover el personaje a la derecha.
Flechas hacia arriba / Tecla W / Barra espaciadora: El personaje salta.

@c Subsection 3: Diseño de Interfaz/GUI
@node Diseño de Interfaz/GUI
@subsection Diseño de Interfaz/GUI

Turno del futuro:
El interfaz del turno del futuro es una simulacion de una pantalla de una sala de camaras,
donde a la derecha tendremos el menu de trampas y a la izquierda el mapa (mismo del turno del 
presente, pero con indicaciónes) adonde pondremos las trampas.

Turno de presente:
El interfaz o mapa es un campo vertical con plataformas estaticas (ambos turnos) y móbiles 
(turno del presente). El fondo del mapa esta de acuerdo con la tematica del comic y no cambia 
conforme el jugador avanza de nivel.

@c Subsection 4: Wireframes de interfaz
@node @i{Wireframes} de interfaz
@subsection @i{Wireframes} de interfaz


@c Subsection 5: Diagramas de contextos/flujo
@node Diagramas de contextos/flujo
@subsection Diagramas de contextos/flujo

Turno del Futuro:
1. El mapa del juego aparece (a la izquierda de la pantalla) con zonas de trampas visibles y el menu de trampas (a la derecha de la pantalla).
2. El jugador selecciona la trampa en el menu de trampas, que desea colocar en el mapa.
3. El jugador hace click en el mapa en el sitio que quiere poner la trampa seleccionada.
4. El jugador sigue poniendo trampas hasta cuando quiera (control de dinero) o hasta que no pueda mas (por un limite preestablecido por fase).
5. El jugador termina el turno del futuro y el turno del presente empieza.

Turno del presente:
1. El personaje aparece en alguna parte de la zona superior del mapa (dependiendo de la fase) encima de una plataforma.
2. El jugador mueve el personaje por las plataformas con la intencion de ir bajando en el mapa encuanto se esquiva/evita los obstaculos y 
recoge monedas y corazones.
3. El jugador llega en una plataforma al limite inferior del mapa, donde recoge una cantidad mayor de dinero y el turno termina.
