@c Section 3: Diseño de Flujo o Gameplay Loop
@node Diseño de Flujo o Gameplay Loop
@section Diseño de Flujo o Gameplay Loop

@menu
* Diagramas de flujo de acciones/fases:: ...
@end menu

@c Subsection 1: Diagramas de flujo de acciones/fases
@node Descripción/fases del bucle interactivo/jugable
@subsection Diagramas de flujo de acciones/fases

@center @image{img/flowchart, 14.5cm,, Flowchart,}
