@c Section 4: Elementos de Juego y comportamientos
@node Elementos de juego y comportamientos
@section Elementos de juego y comportamientos

@menu
* Personajes:: ...
* Habilidades:: ...
* Trampas:: ...
* Diagramas de flujo y autómatas de comportamiento de los elementos/agentes:: ...
* Ilustraciones:: ...
@end menu

@c Subsection 1: Personajes
@node Personajes
@subsection Personajes

En este apartado se desglosarán los personajes que aparecen en el videojuego, tanto jugables por el usuario o con otro tipo de rol en la narrativa.

@float Table,characters
@shortcaption{Tabla de personajes}
@caption{Tabla de personajes}
@multitable @columnfractions .2 .2 .25 .4
@c Column Names
@headitem Nombre @tab IMG @tab Rol @tab Descripción
@c Row 1
@item @i{Elon J. D'Oroski} (presente)
@tab (...)
@tab Jugable durante el descenso.
@tab Personaje protagonista en el presente.
@c Row 2
@item @i{Elon J. D'Oroski} (futuro)
@tab (...)
@tab Jugable durante la colocación de trampas.
@tab Personaje protagonista en su versión futura (+50 años).
@c Row 3
@item Blockchainy
@tab (...)
@tab Montura, usable como habilidad.
@tab (...)
@end multitable
@end float

@c Subsection 2: Habilidades
@node Habilidades
@subsection Habilidades

En cada ronda, cuando se inicia el turno del presente, se dará la oportunidad al jugador de comprar ciertas habilidades, las cuales aportarán diversos atributos que podrían llegar a ayudar al protagonista a superar ciertos obstáculos, mas solo se podrán utilizar durante esa ronda.

@float Table,skills
@shortcaption{Tabla de habilidades}
@caption{Tabla de habilidades}
@multitable @columnfractions .25 .25 .25 .25
@c Column Names
@headitem Nombre @tab IMG @tab Disponibilidad @tab Precio
@c Row 1
@item (...)
@tab (...)
@tab (...)
@tab (...)
@c Row 2
@item (...)
@tab (...)
@tab (...)
@tab (...)
@c Row 3
@item (...)
@tab (...)
@tab (...)
@tab (...)
@c Row 4
@item (...)
@tab (...)
@tab (...)
@tab (...)
@end multitable
@end float

@c Subsection 3: Trampas
@node Trampas
@subsection Trampas

El sistema de trampas es la mecánica más importante del juego, 

@menu
* Categorías de trampas y sus propiedades:: ...
* Compendio general de trampas:: ...
@end menu

@c Subsubsection 1: Categorías de trampas y sus propiedades
@node Categorías de trampas y sus propiedades
@subsubsection Categorías de trampas y sus propiedades

(...)

@float Table,trap-categories
@shortcaption{Categorías de las trampas}
@caption{Categorías de las trampas}
@table @samp
@item Tier 1: DOGE
(...)
@item Tier 2: Ethereum
(...)
@item Tier 3: Bitcoin
(...)
@end table
@end float

@c Subsubsection 2: Compendio general de trampas
@node Compendio general de trampas
@subsubsection Compendio general de trampas

(...)

@float Table,trap-list
@shortcaption{Tabla de trampas con @i{stats}}
@caption{Tabla de trampas con @i{stats}}
@multitable @columnfractions .2 .2 .2 .2 .2
@c Column Names
@headitem Nombre @tab IMG @tab Categoría @tab Disponibilidad @tab Valor
@c Row 1
@item Sierra cortadora
@tab @image{img/traps/tier-1/spinning-saw,2cm,,Sierra cortadora,}
@tab DOGE
@tab R1
@tab 200
@c Row 2
@item (...)
@tab (...)
@tab (...)
@tab (...)
@tab (...)
@c Row 3
@item (...)
@tab (...)
@tab (...)
@tab (...)
@tab (...)
@c Row 4
@item (...)
@tab (...)
@tab (...)
@tab (...)
@tab (...)
@end multitable
@end float

@c Subsection 4: Diagramas de flujo y autómatas de comportamiento de los elementos/agentes
@node Diagramas de flujo y autómatas de comportamiento de los elementos/agentes
@subsection Diagramas de flujo y autómatas de comportamiento de los elementos/agentes

(...)

@c Subsection 5: Ilustraciones
@node Ilustraciones
@subsection Ilustraciones

(...)
