@c Section 4: Elementos de Juego y Comportamientos
@node Elementos de Juego y Comportamientos
@section Elementos de Juego y Comportamientos

@menu
* Personajes:: ...
* Habilidades:: ...
* Trampas:: ...
* Diagramas de flujo y autómatas de comportamiento de los elementos/agentes:: ...
* Ilustraciones:: ...
@end menu

@c Subsection 1: Personajes
@node Personajes
@subsection Personajes

(...)

@float Table,characters
@multitable @columnfractions .2 .2 .25 .4
@c Column Names
@headitem Nombre @tab IMG @tab Rol @tab Descripción
@c Row 1
@item @i{Elon J. D'Oroski} (presente)
@tab (...)
@tab Jugable durante el descenso.
@tab Personaje protagonista en el presente.
@c Row 2
@item @i{Elon J. D'Oroski} (futuro)
@tab (...)
@tab Jugable durante la colocación de trampas.
@tab Personaje protagonista en su versión futura (+50 años).
@c Row 3
@item Blockchainy
@tab (...)
@tab Montura, usable como habilidad.
@tab (...)
@end multitable
@end float

@c Subsection 2: Habilidades
@node Habilidades
@subsection Habilidades

(...)

@c Subsection 3: Trampas
@node Trampas
@subsection Trampas

@menu
* Categorías de trampas y sus propiedades:: ...
* Compendio general de trampas:: ...
@end menu

@c Subsubsection 1: Categorías de trampas y sus propiedades
@node Categorías de trampas y sus propiedades
@subsubsection Categorías de trampas y sus propiedades

(...)

@float Table,trap-categories
@table @samp
@item Tier 1: (...)
(...)
@item Tier 2: (...)
(...)
@item Tier 3: (...)
(...)
@end table
@end float

@c Subsubsection 2: Compendio general de trampas
@node Compendio general de trampas
@subsubsection Compendio general de trampas

(...)

@float Table,trap-list
@multitable @columnfractions
@c Column Names
@headitem Nombre @tab IMG @tab Categoría @tab Disponibilidad
@c Row 1
@item (...)
@tab (...)
@tab (...)
@tab (...)
@c Row 2
@item (...)
@tab (...)
@tab (...)
@tab (...)
@c Row 3
@item (...)
@tab (...)
@tab (...)
@tab (...)
@c Row 4
@item (...)
@tab (...)
@tab (...)
@tab (...)
@end multitable
@end float

@c Subsection 4: Diagramas de flujo y autómatas de comportamiento de los elementos/agentes
@node Diagramas de flujo y autómatas de comportamiento de los elementos/agentes
@subsection Diagramas de flujo y autómatas de comportamiento de los elementos/agentes

(...)

@c Subsection 5: Ilustraciones
@node Ilustraciones
@subsection Ilustraciones

(...)
