@c Section 4: Elementos de Juego y Comportamientos
@node Elementos de Juego y Comportamientos
@section Elementos de Juego y Comportamientos

@menu
* Personajes@comma{} agentes@comma{} ítems@comma{} u otros elementos del Gameworld:: ...
* Listados y descripciones de elementos:: ...
* Taxonomías y categorías:: ...
* Tablas con estadísticas y valores:: ...
* Diagramas de flujo y autómatas de comportamiento de los elementos/agentes:: ...
* Ilustraciones:: ...
@end menu

@c Subsection 1: Personajes, agentes, ítems, u otros elementos del Gameworld
@node Personajes@comma{} agentes@comma{} ítems@comma{} u otros elementos del Gameworld
@subsection Personajes@comma{} agentes@comma{} ítems@comma{} u otros elementos del Gameworld

(...)

@c Subsection 2: Listados y descripciones de elementos
@node Listados y descripciones de elementos
@subsection Listados y descripciones de elementos

(...)

@c Subsection 3: Taxonomías y categorías
@node Taxonomías y categorías
@subsection Taxonomías y categorías

(...)

@c Subsection 4: Tablas con estadísticas y valores
@node Tablas con estadísticas y valores
@subsection Tablas con estadísticas y valores

(...)

@c Subsection 5: Diagramas de flujo y autómatas de comportamiento de los elementos/agentes
@node Diagramas de flujo y autómatas de comportamiento de los elementos/agentes
@subsection Diagramas de flujo y autómatas de comportamiento de los elementos/agentes

(...)

@c Subsection 6: Ilustraciones
@node Ilustraciones
@subsection Ilustraciones

(...)
