@c Section 2.5: Diseño de unidades jugables
@node Diseño de unidades jugables
@section Diseño de unidades jugables

@menu
* Mapa y entorno:: ...
* Rondas y turnos:: ...
@end menu

@c Subsection 2.5.1: Mapa y entorno
@node Mapa y entorno
@subsection Mapa y entorno

@float Figure,map-draft
@shortcaption{Esbozo del mapa}
@caption{Esbozo del mapa}
@center @image{img/mapa,10cm,,Mapa,}
@end float

@page

@float Figure,pixel-map
@shortcaption{Mapa en @i{pixel art}}
@caption{Mapa en @i{pixel art}}
@center @image{img/pixel-map,3cm,,Mapa en @i{pixel art},}
@end float

@page

Habrá distintos tipos de plataformas con la intención de aumentar la dificultad y mejorar la experiencia del juego. Estas son:
@itemize @bullet
@item @b{Plataforma estática:}
La plataforma no se mueve ni interactúa de forma dinámica con el personaje.
@item @b{Plataforma de movimiento:}
La plataforma se mueve en dirección horizontal o vertical haciendo con que el jugador tenga que esperar el momento correcto para poder avanzar.
@item @b{Plataforma inclinada:}
La plataforma se inclina cuando el jugador se mueve a una de sus extremidades. Eso hace que el jugador tenga que mantenerse en el centro de la plataforma y que se mueva rápidamente cuando salte a otra plataforma.
@item @b{Plataforma resbaladiza:}
Las plataformas son resbaladizas (cuando el jugador deja de presionar un botón de dirección el personaje sigue moviéndose con aceleración descendente hacia la dirección indicada) haciendo con que el jugador tenga más cuidado con el control de movimiento.
@item @b{Plataforma explosiva:}
Las plataformas se ponen en tono rojo claro gradualmente y explotan después de 3 segundos, si el personaje no cambia de plataforma, simplemente cae, sin perder vidas. Eso hace que el personaje no pueda esperar en esa plataforma y tenga que moverse rápidamente a otra.
@end itemize

@c Subsection 2.5.2: Rondas y turnos
@node Rondas y turnos
@subsection Rondas y turnos

Aparecerá en cada ronda un contador que simbolizaría el año en que el personaje principal
se encuentra (el año inicial es el 3055) y aumenta conforme el personaje baja por el mapa. El año en el contador @b{aumenta en 1} cada vez que el jugador pase de ronda.
