@c Section 5: Desarrollo Ludonarrativo
@node Desarrollo Ludonarrativo
@section Desarrollo Ludonarrativo

@menu
* Diagramas de flujo y autómatas:: ...
@end menu

@c Subsection 1: Diagramas de flujo y autómatas
@node Diagramas de flujo y autómatas
@subsection Diagramas de flujo y autómatas

@center @image{img/flowchart,,, Flowchart,}
