@c Section 6: Diseño de Unidades de Gameplay
@node Diseño de Unidades de Gameplay
@section Diseño de Unidades de Gameplay

@menu
* Diagramas de diseño de niveles:: ...
* Mapas de niveles y entornos:: ...
* Especificación de puzzles:: ...
* Mapas de secuencia de resolución de fases:: ...
* Tablas y calendarios de fases:: ...
@end menu

@c Subsection 1: Mapas de secuencia de resolución de fases
@node Tablas de secuencia de resolución de fases
@subsection Tablas de secuencia de resolución de fases 

Conforme pasan los niveles se desbloquean trampas y habilidades y el limite de trampas por 
nivel aumenta. A los 30-35 niveles, ya deberia estar todo desbloqueado.

Tabla de habilidades:
(...)
Tabla de obstaculos:
(...)
Limite de trampas por cada nivel:
(...)

@c Subsection 5: Tablas y calendarios de fases
@node Tablas y calendarios de fases
@subsection Tablas y calendarios de fases

Aparecera en cada ronda un contador que simbolizaria el año en que el personaje principal
se encuentra (primer año es el 3055) y aumenta conforme el personaje baja en el mapa. El primer 
año en el contador aumenta (cantidad a decidir) conforme el jugador pase de rondas.
