@c Section 2: Desglose
@node Desglose
@section Desglose

@menu
* Diseño:: ...
* Motor:: ...
* Recursos audioviuales o assets:: ...
@end menu

@c Subsection 1: Diseño
@node Diseño
@subsection Diseño

(...)

@c Subsection 2: Motor
@node Motor
@subsection Motor

Costes de desarrollo de las mecánicas:

@itemize @bullet
@item
@b{Sistema de cambio de turnos:} Medio
@item
@b{Movimiento del personaje:} Medio
@item
@b{Habilidades del personaje:} Bajo
@item
@b{Sistema de colocación de trampas:} Alto
@item
@b{Mecánicas de las trampas:} Bajo
@item
@b{Sistema económico:} Medio
@end itemize


@c Subsection 3: Recursos audioviuales o assets
@node Recursos audioviuales o assets
@subsection Recursos audioviuales o assets

(...)
