@c Section 2: Desglose
@node Desglose
@section Desglose

@menu
* Diseño:: ...
* Motor:: ...
* Recursos audioviuales o assets:: ...
@end menu

@c Subsection 1: Diseño
@node Diseño
@subsection Diseño

Costes de desarrollo del diseño:

@itemize @bullet
@item
@b{Diseño de general:} Alto
@item
@b{Diseño de personaje:} Medio
@item
@b{Diseño de personaje antagonista:} Medio
@item
@b{Diseño de trampas:} Medio
@item
@b{Diseño de proyectiles:} Bajo
@item
@b{Diseño de plataformas:} Bajo
@item
@b{Diseño de escenario:} Bajo
@item
@b{Diseño de background:} Medio
@item
@b{Diseño de menús:} Bajo
@item
@b{Diseño de viñetas:} Alto
@item
@b{Diseño de turno del antagonista:} Alto
@end itemize

@c Subsection 2: Motor
@node Motor
@subsection Motor

Costes de desarrollo de las mecánicas:

@itemize @bullet
@item
@b{Sistema de cambio de turnos:} Medio
@item
@b{Movimiento del personaje:} Medio
@item
@b{Habilidades del personaje:} Bajo
@item
@b{Sistema de colocación de trampas:} Alto
@item
@b{Mecánicas de las trampas:} Bajo
@item
@b{Sistema económico:} Medio
@end itemize


@c Subsection 3: Recursos audiovisuales o assets
@node Recursos audioviuales o assets
@subsection Recursos audioviuales o assets

Costes de desarrollo de los recursos audiovisuales:

@itemize @bullet
@item
@b{Banda sonora:} Medio
@item
@b{Efectos de trampas:} Medio
@item
@b{Animaciones de personaje:} Bajo
@item
@b{Animaciones de cambio de personaje:} Alto
@item
@b{Movimiento de cambio de viñeta:} Bajo
@item
@b{Despliegues de menu:} Medio
@end itemize
