name: Documentation

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-20.04
    steps:
      - name: Install needed dependencies
        run: |
          sudo apt update && sudo apt install -y texlive texinfo make
      - name: Build the documentation
        run: |
          ls -la && cd Documentation && make
