name: Documentation

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Install needed dependencies
        run: |
          sudo apt update && sudo apt install -y texlive-full texinfo ghostscript make
      - name: Build the documentation
        run: |
          ls -la && cd Documentation && make
